name: Install Conda
defaults:
  run:
    shell: bash -l {0}

inputs:
  python-version:
    required: true

  # path:
  #   required: true

  # force-install:
  #   required: false
  #   default: false

runs:
  using: composite
  steps:
    # - name: Get Date
    #   - name: Set cache date
    #     run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV


      # If cache not found, install python
    - name: Set up Python ${{ inputs.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: mambaforge
        miniforge-version: latest
        python-version: ${{ inputs.python-version }}
        activate-environment: devel
        environment-file: environment.yml
        use-only-tar-bz2: true

    - name: Install requirements
      shell: bash -l {0}
      run: mamba env update -n devel -f environment.yml

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: conda-${{ runner.os }}-${{ inputs.python-version}}-${{ hashFiles('environment.yml') }}
      id: cache

    # If cache not found, create the environment
    # - name: Install requirements
    #   shell: bash -l {0}
    #   run: mamba env update -n devel -f environment.yml
