name: Run Build
defaults:
  run:
    shell: bash -l {0}

inputs:
  python-version:
    required: true
  repo-token:
    required: true

runs:
  using: composite
  steps:

#    Windows steps
    - name: Pytest ${{ runner.os }} x ${{ inputs.python-version}}
      # if: startsWith(runner.os, 'win')
      shell: bash -l {0}
      run: |
        conda activate devel
        pip install -e .
        pytest -v --junitxml=test-results-_${{ runner.os }}.xml --color=yes
        # mv examples/data/14061619.png examples/data/14061619_${{ runner.os }}.png

    - name: Publish Test Results Win
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: startsWith(runner.os, 'win')
      with:
        files: "test-results-_${{ runner.os }}.xml"

    - name: Publish Test Results Max/Linux
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: startsWith(runner.os, 'lin') || startsWith(runner.os, 'mac')
      with:
        files: "test-results-_${{ runner.os }}.xml"

    # Publish those artifacts for this build so testers can view them.
    - uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: examples/data/


    - name: Build ${{runner.os}} x ${{ inputs.python-version}}
      if: startsWith(runner.os, 'win')
      shell: bash -l {0}
      run: |
        cd runsharp
        pyinstaller SHARPpy-win7-64.spec --log-level DEBUG
        cd ..

    # - uses: actions/upload-artifact@v3
    #   if: startsWith(runner.os, 'win')
    #   with:
    #     name:
    #     path: |
    #     runsharp/dist/
    #     runsharp/dist/

    - name: Archive ${{ runner.os }} release
      uses: thedoctor0/zip-release@main
      # if: startsWith(runner.os, 'win')
      with:
        type: 'zip'
        filename: 'SHARPpy-${{runner.os}}.zip'
        path: runsharp/dist/SHARPpy.exe

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.repo-token }}
        default_bump: 'minor'

    - name: Create ${{ runner.os }} release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SHARPpy-${{ runner.os }}.zip"
        allowUpdates: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

        # commit: 'master'
        # token: ${{ secrets.GITHUB_TOKEN }}
