name: Run Build
defaults:
  run:
    shell: bash -l {0}

inputs:
  python-version:
    required: true

runs:
  using: composite
  steps:

    - name: build ${{ runner.os}} x ${{ inputs.python-version}}
      if: startsWith(runner.os, 'win')
      shell: bash -l {0}
      run: |
        conda activate devel
        pip install -e .
        pytest -v --junitxml=test-results.xml --color=yes

        cd runsharp
        pyinstaller SHARPpy-win7-64.spec --log-level DEBUG

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: startsWith(runner.os, 'win')
      with:
        files: "test-results.xml"

    # - name: Publish Test Results
    #     uses: EnricoMi/publish-unit-test-result-action@v1
    #     if: startsWith(runner.os, 'lin') || startsWith(runner.os, 'mac')
    #     with:
    #       files: "test-results.xml"

    # - uses: actions/upload-artifact@v3
    #   if: startsWith(runner.os, 'win')
    #   with:
    #     name: SHARPpy.exe
    #     path: runsharp/dist/ # or path/to/artifact
