name: Run Release
defaults:
  run:
    shell: bash -l {0}

inputs:
  repo-token:
    required: true
  tag:
    required: true

runs:
  using: composite
  steps:
    # Tag and release if pushed to main -----------------------
    # - name: Get existing tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v6.0
    #   with:
    #     github_token: ${{ inputs.repo-token }}
    #     default_bump: patch
    #
    # - name: ${{ steps.tag_version.outputs.previous_tag }}
    #   shell: bash -l {0}
    #   run: echo ${{ steps.tag_version.outputs.previous_tag }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        # artifacts: "SHARPpy-*.zip"
        token: ${{ inputs.repo-token }}
        allowUpdates: true
        tag: ${{ inputs.tag }}
    #     tag: ${{ steps.tag_version.outputs.previous_tag }}
