name: build
on:
  push:
    branches:
      - main
    tags:
      - v*
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * *'


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    # Control the os/python builds
    strategy:
      matrix:
        python-version: [3.9]
        include:
          - os: [macos-latest, windows-latest]

    name: ${{ matrix.os }} Build and Release
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

      # Installs environment
    - name: Install Conda and Environment
      uses: ./.github/actions/install-conda
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build binaries
      uses: ./.github/actions/run-build

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: ./.github/actions/run-release
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
