name: documentation
on:
  push:
    # paths:
    #   - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # This off the shelf is faster, but doesn't support autodoc/sphinx_gallery
    # - name: Build sphinx docs
    #   uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"

    # Manual install - works but takes longer
    - name: Install Conda and Environment
      uses: ./.github/actions/install-conda
      with:
        python-version: 3.9

    - name: Build documents
      shell: bash -l {0}
      run: |
        conda activate devel
        pip install -e .

        cd docs

        cp ../LICENSE.rst ../docs/source/license.rst
        cp ../CONTRIBUTING.rst ../docs/source/contributing.rst
        cp ../CHANGELOG.rst ../docs/source/changelog.rst

        make html

        touch build/html/.nojekyll

        cd ..

    - name: Deploy docs to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/build/html/
        clean: true
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        clean-exclude: |
          .nojekyll
          *.md
