name: pytest

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * *'

# concurrency:
#   group: ${{ github.workflow}}-${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    # Control the os/python builds
    strategy:
      matrix:
        python-version: [3.8]
        include:
          # - os: ubuntu-latest
          #   label: linux-64
          #   path: /usr/share/miniconda3/envs/my-env

          - os: macos-latest
            label: osx-64
            path: /Users/runner/miniconda3/envs/my-env
          #
          # - os: windows-latest
          #   label: win-64
          #   path: C:\Miniconda3\envs\my-env


    name: ${{ matrix.label }} x Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      # Checks out the repo onto vm
    - name: Checkout source
      uses: actions/checkout@v3

      # Installs environment cache not found
    - name: Install conda and environment
      if: steps.cache.outputs.cache-hit != 'true'
      uses: ./.github/actions/install-conda
      with:
        python-version: ${{ matrix.python-version }}
        path: ${{ matrix.path }}
        force-install: false

    # - name: Run sharppy build
    #   shell: bash -l {0}
    #   uses: ./.github/actions/run-build
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     oslabel: ${{ matrix.label }}
