name: pytest

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * *'

# concurrency:
#   group: ${{ github.workflow}}-${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    # Control the os/python builds
    strategy:
      matrix:
        python-version: [3.8]
        include:
          # - os: ubuntu-latest
          #   label: linux-64
          #   path: /usr/share/miniconda3/envs/devel

          # - os: macos-latest
          #   label: osx-64
          #   path: /Users/runner/miniconda3/envs/devel
          #
          - os: windows-latest
            label: win-64
            path: C:\Miniconda3\envs\devel

    name: ${{ matrix.label }} x Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
    # - name: Get Date
    #   - name: Set cache date
    #     run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    #

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    # - name: Checkout cache
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/conda_pkgs_dir
    #     # path: ${{ env.pythonLocation }}
    #     key: conda-${{ runner.os }}-${{ inputs.python-version}}-${{ hashFiles('environment.yml') }}
    #   id: cache

      # Installs environment cache not found
    - name: Install conda and environment
      uses: ./.github/actions/install-conda
      with:
        python-version: ${{ matrix.python-version }}
      # if: ${{ steps.cache.outputs.cache-hit != 'true' }}

    - name: Run sharppy build
      uses: ./.github/actions/run-build
      with:
        python-version: ${{ matrix.python-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
