name: pytest
on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    # Control the os/python builds
    name: Pytest ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

      # Installs environment
    - name: Install Conda and Environment
      uses: ./.github/actions/install-conda
      with:
        python-version: 3.8

    - name: Run Pytest
      uses: ./.github/actions/run-test

    # Unused --------------------------
    # - name: EQUIV check ${{runner.os}} x ${{ inputs.python-version}}
    #   shell: bash -l {0}
    #   run: |
    #     OS=${{runner.os}}
    #     echo ${OS:0:3}
    #     if [[ "${OS:0:3}" == "mac" ]]; then
    #       echo "pyinstaller SHARPpy-mac-64.spec --log-level DEBUG"
    #     elif [[ "${OS:0:3}" == "Win" ]]; then
    #       echo "pyinstaller SHARPpy-win7-64.spec --log-level DEBUG"
    #     else
    #       echo "Linux"
    #     fi

    # - name: Checkout cache
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/conda_pkgs_dir
    #     # path: ${{ env.pythonLocation }}
    #     key: conda-${{ runner.os }}-${{ inputs.python-version}}-${{ hashFiles('environment.yml') }}
    #   id: cache

    # if: ${{ steps.cache.outputs.cache-hit != 'true' }}
