name: workflow-test
on:
  push:
  tags:
    - test

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    # Control the os/python builds
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        # include:
          # - os: [macos-latest, ubuntu-latest, windows-latest]

    # name: ${{ matrix.os }} x Python ${{ matrix.python-version }}
    # runs-on: ${{ matrix.os }}

    name: Ubuntu x Python 3.8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - name: Get existing tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false

    - run: echo ${{steps.tag_version.outputs.new_tag}}
